//! CJK-capable font chain for egui (DESIGN.md §15).
//!
//! egui's built-in fonts cover Latin + a monochrome emoji subset only, so we
//! append a CJK fallback chain to the Proportional/Monospace families:
//!
//! 1. `msyh.ttc` (Microsoft YaHei) from `%SystemRoot%\Fonts` — best looking,
//!    always present on real Windows installs (TTC index 0 is used, which is
//!    the regular face — ab_glyph picks face 0 for collections);
//! 2. `assets/fonts/NotoSansSC-Subset.otf` — the bundled SIL-OFL fallback for
//!    stripped/enterprise Windows images (runtime file, shipped next to the
//!    exe like `data/`; generated by `tools/make_font_subset.py`);
//! 3. `simhei.ttf` / `simsun.ttc` — last-ditch system fonts for rare glyphs.
//!
//! Every candidate is optional: unreadable files are skipped silently and the
//! chain always ends on egui's built-in Latin fonts. The chain is installed
//! in BOTH language modes — even in English the player's HOI4 save may carry
//! CJK division names that must not render as tofu.

use bevy::prelude::*;
use bevy_egui::{egui, EguiContexts};
use std::path::PathBuf;

/// Font candidates, highest priority first: (egui font name, path).
fn candidates() -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    let win_fonts = std::env::var_os("SystemRoot")
        .map(PathBuf::from)
        .map(|r| r.join("Fonts"));
    if let Some(dir) = &win_fonts {
        out.push(("CJK-YaHei".into(), dir.join("msyh.ttc")));
    }
    // Bundled fallback font: next to the exe in shipped packages (recognized
    // by the sibling `data/` dir), else under the dev workspace root.
    let pkg_root = std::env::current_exe()
        .ok()
        .and_then(|exe| exe.parent().map(|d| d.to_path_buf()))
        .filter(|dir| dir.join("data").is_dir())
        .unwrap_or_else(|| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("..")
                .join("..")
        });
    out.push((
        "CJK-NotoSC".into(),
        pkg_root
            .join("assets")
            .join("fonts")
            .join("NotoSansSC-Subset.otf"),
    ));
    if let Some(dir) = &win_fonts {
        out.push(("CJK-SimHei".into(), dir.join("simhei.ttf")));
        out.push(("CJK-SimSun".into(), dir.join("simsun.ttc")));
    }
    out
}

/// Install the chain onto an egui context (idempotent in practice — call
/// once via [`install_ui_fonts_once`]).
pub fn install_ui_fonts(ctx: &egui::Context) {
    let mut fonts = egui::FontDefinitions::default();
    let mut names: Vec<String> = Vec::new();
    for (name, path) in candidates() {
        match std::fs::read(&path) {
            Ok(bytes) if !bytes.is_empty() => {
                fonts
                    .font_data
                    .insert(name.clone(), egui::FontData::from_owned(bytes));
                names.push(name);
            }
            _ => {} // missing/unreadable candidate — skip silently
        }
    }
    if names.is_empty() {
        return;
    }
    for family in [egui::FontFamily::Proportional, egui::FontFamily::Monospace] {
        if let Some(list) = fonts.families.get_mut(&family) {
            list.extend(names.iter().cloned());
        }
    }
    ctx.set_fonts(fonts);
}

/// Bevy system: install fonts exactly once, as soon as the egui context
/// exists. `try_ctx_mut` because the context is not ready on the very first
/// frame, where `ctx_mut()` would panic.
pub fn install_ui_fonts_once(mut contexts: EguiContexts, mut done: Local<bool>) {
    if *done {
        return;
    }
    let Some(ctx) = contexts.try_ctx_mut() else {
        return;
    };
    install_ui_fonts(ctx);
    *done = true;
}
