//! Build script: embed the program icon (`assets/icon.ico`, generated by
//! `tools/make_icon.py`) into the Windows exe as icon resource id 1, so
//! Explorer/taskbar/alt-tab show the Forward Command hex counter. The runtime
//! window icon (`app_icon.rs`) WM_SETICONs the same resource id.
//!
//! windres is invoked directly instead of via the embed-resource crate:
//! embed-resource hardcodes plain `windres` for gnu targets, which on the
//! dev machine resolves to WinLibs GNU windres (WinLibs must lead PATH for
//! dlltool — see run_test.ps1). GNU windres shells out to cc1 for
//! preprocessing with UNQUOTED paths and dies on the space in
//! "Forward Command"; llvm-windres preprocesses internally and handles the
//! quoted path fine, so it is preferred when present.
//!
//! The .rc is generated into OUT_DIR with an absolute, forward-slash path
//! to the .ico — spaces stay quoted, and no canonicalize() `\\?\` prefix
//! confuses windres.

use std::{
    env, fs,
    path::PathBuf,
    process::{Command, Stdio},
};

fn main() {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // crates/tactical3d-bin -> workspace root -> assets/icon.ico
    let ico = manifest
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("assets")
        .join("icon.ico");
    assert!(ico.is_file(), "program icon missing: {}", ico.display());
    println!("cargo:rerun-if-changed={}", ico.display());

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let rc = out_dir.join("app-icon.rc");
    let ico_fwd = ico.display().to_string().replace('\\', "/");
    fs::write(&rc, format!("1 ICON \"{ico_fwd}\"\r\n")).unwrap();

    let windres = ["llvm-windres", "windres"]
        .into_iter()
        .find(|exe| runnable(exe))
        .expect("no windres on PATH (need llvm-windres or GNU windres)");
    let out = out_dir.join("app-icon.res");
    let status = Command::new(windres)
        .arg("--target")
        .arg("pe-x86-64")
        .args(["-c", "65001"]) // UTF-8 codepage
        .arg("--input")
        .arg(&rc)
        .arg("--output")
        .arg(&out)
        .arg("--include-dir")
        .arg(&out_dir)
        .arg("--output-format=coff")
        .status()
        .unwrap_or_else(|e| panic!("failed to run {windres}: {e}"));
    assert!(status.success(), "{windres} failed with {status}");

    // Same linking directive embed-resource emits (rustc >= 1.50).
    println!("cargo:rustc-link-arg-bins={}", out.display());
}

fn runnable(exe: &str) -> bool {
    Command::new(exe)
        .arg("--version")
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}
